project:
  seed: 42

data:
  raw_url: "https://archive.ics.uci.edu/ml/machine-learning-databases/00601/ai4i2020.csv"
  raw_path: "data/raw/ai4i2020.csv"
  processed_path: "data/processed/ai4i2020_processed.csv"
  train_path: "data/processed/train.csv"
  test_path: "data/processed/test.csv"

preprocessing:
  drop_columns: ['UID', 'Product ID', 'TWF', 'HDF', 'PWF', 'OSF', 'RNF']
  target_col: 'Machine failure'
  time_index_col: 'UID'

mining:
  apriori_min_support: 0.01
  apriori_min_lift: 1.5
  kmeans_clusters: 3

modeling:
  test_size: 0.2
  semi_supervised_labeled_ratio: 0.2
  self_training_threshold: 0.85